import type { RawEntry } from '../db'

/**
 * Generated by scripts/build-deck.mjs - do not edit by hand.
 *
 * 279 hand-written entries, then 721 drawn from WordNet 3.0.
 *
 * WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.
 * Used under the WordNet licence, which permits use, copying, modification and
 * distribution provided this notice travels with it.
 *
 * Word choice uses frequency ranks over the Google Web Trillion Word Corpus
 * (ranks 20,000-1,50,000): common enough to meet, uncommon enough to be worth learning.
 */
const TSV = `
abate	verb	to become less intense or widespread; to reduce something
aberration	noun	a departure from what is normal or expected
abhor	verb	to regard with disgust and hatred
abounding	adjective	existing in abundance
absenteeism	noun	habitual absence from work
abstain	verb	to choose not to do or take something
accolade	noun	an award, or an expression of praise
accusation	noun	a formal charge of wrongdoing brought against a person; the act of imputing blame or guilt
accusative	noun	the case of nouns serving as the direct object of a verb
accustom	verb	make psychologically or physically used
acrimonious	adjective	marked by strong resentment or cynicism
acuity	noun	sharpness of vision; the visual ability to resolve fine detail
acumen	noun	sharp judgment and quick insight
adamant	adjective	refusing to be persuaded; unshakably firm
adenoma	noun	a benign epithelial tumor of glandular origin
adjoin	verb	lie adjacent to another or share a boundary
admiration	noun	a feeling of delighted approval and liking
admonish	verb	to warn or reprimand gently but firmly
adventitious	adjective	associated by chance and not an integral part
adversity	noun	a difficult or unpleasant situation
aerosolized	adjective	in the form of ultramicroscopic solid or liquid particles dispersed or suspended in air or gas
aesthetic	adjective	concerned with beauty, or with the appreciation of beauty
affable	adjective	friendly and easy to talk to
affective	adjective	characterized by emotion
afforestation	noun	the conversion of bare or cultivated land into forest
afield	adverb	far away from home or one's usual surroundings
alleviate	verb	to make pain or a problem less severe
alliteration	noun	use of the same consonant at the beginning of each stressed syllable in a line of verse
aloof	adjective	distant and uninvolved; emotionally cool
altruism	noun	unselfish concern for the welfare of others
amateurish	adjective	lacking professional skill or expertise
ambiguous	adjective	open to more than one interpretation; unclear
ambivalent	adjective	having mixed or contradictory feelings about something
amenable	adjective	disposed or willing to conform
amity	noun	a cordial disposition
ampersand	noun	a punctuation mark (&) used to represent conjunction
amplify	verb	increase in size, volume or significance
anachronism	noun	something placed in the wrong historical period
analgesic	adjective	capable of relieving pain
analogous	adjective	comparable in some useful respect
anecdote	noun	a short personal story used to illustrate a point
animatronics	noun	the construction of robots to look like animals
animosity	noun	strong hostility or ill will
annexation	noun	incorporation by joining or uniting
anomaly	noun	something that deviates from the standard or expected
anonym	noun	a fictitious name used when the person performs a particular social role
anorectal	adjective	pertaining to the anus and rectum considered together
antipathy	noun	a deep-seated dislike
apathy	noun	lack of interest, enthusiasm, or concern
appease	verb	to pacify someone by giving in to their demands
arbitrary	adjective	based on personal whim rather than reason or rule
arcane	adjective	understood by very few; mysteriously obscure
arduous	adjective	requiring great effort; strenuous
armory	noun	a collection of resources
artful	adjective	not straightforward or candid; giving a false appearance of frankness
articulate	adjective	able to express thoughts clearly and fluently
ascetic	noun	a person who practices severe self-discipline and abstinence
assassinate	verb	murder; especially of socially prominent persons
assiduous	adjective	showing great care and persistent effort
astride	adverb	with one leg on each side
astute	adjective	shrewd; quick to see an advantage
atheistic	adjective	rejecting any belief in gods
attest	verb	provide evidence for; stand as proof of; show by one's behavior, attitude, or external attributes
audacious	adjective	boldly daring, sometimes to the point of recklessness
augment	verb	to make greater by adding to it
auspicious	adjective	suggesting a favorable outcome; promising
austere	adjective	severely simple and plain; stern in manner
autoradiography	noun	producing a radiograph by means of the radiation emitted from the specimen being photographed
avocation	noun	an auxiliary activity
awkwardness	noun	unskillfulness resulting from a lack of training
baccalaureate	noun	a farewell sermon to a graduating class at their commencement ceremonies
bahasa	noun	the dialect of Malay used as the national language of the Republic of Indonesia or of Malaysia
baldness	noun	the condition of having no hair on the top of the head
baloney	noun	pretentious or silly talk or writing
bamboozle	verb	conceal one's true motives from especially by elaborately feigning good intentions so as to gain an end
banal	adjective	so unoriginal as to be boring
barricaded	adjective	preventing entry or exit or a course of action
battering	noun	the act of subjecting to strong attack
beatification	noun	a state of supreme happiness
belie	verb	to give a false impression of; to contradict
benevolent	adjective	kind and generous toward others
berate	verb	censure severely or angrily
bibliomania	noun	preoccupation with the acquisition and possession of books
billet	noun	a short personal letter
bitterness	noun	a feeling of deep and bitter anger and ill-will
blackness	noun	the quality or state of the achromatic color of least lightness
blaring	adjective	unpleasantly loud and penetrating
blister	noun	a flaw on a surface resulting when an applied substance does not adhere
blurred	adjective	indistinct or hazy in outline
boldness	noun	the trait of being willing to undertake things that involve risk or danger
bolster	verb	to support or strengthen
bonfire	noun	a large outdoor fire that is lighted as a signal or in celebration
boozing	noun	the act of drinking alcoholic beverages to excess
botch	verb	make a mess of, destroy or ruin
bracing	adjective	imparting vitality and energy
braised	adjective	cooked by browning in fat and then simmering in a closed container
breve	noun	a diacritical mark (U-shaped) placed over a vowel to indicate a short sound
brevity	noun	shortness of speech or writing; conciseness
brilliancy	noun	a quality that outshines the usual
bronchospasm	noun	a spasm of the bronchi that makes exhalation difficult and noisy; associated with asthma and bronchitis
bruit	verb	tell or spread rumors
buggery	noun	intercourse via the anus, committed by a man with a man or woman
burnish	verb	polish and make shiny
burnup	noun	a high-speed motorcycle race on a public road
burping	noun	a reflex that expels gas noisily from the stomach through the mouth
cackle	noun	the sound made by a hen after laying an egg
cacophony	noun	a harsh, discordant mixture of sounds
calorimetry	noun	measurement of quantities of heat
candid	adjective	truthful and straightforward, even when it is awkward
capricious	adjective	given to sudden changes of mood or behavior
cardiomyopathy	noun	a disorder (usually of unknown origin) of the heart muscle
carelessness	noun	the quality of not being careful or taking pains
caries	noun	soft decayed area in a tooth; progressive decay can lead to the death of a tooth
castigate	verb	to reprimand severely
causation	noun	the act of causing something to happen
caustic	adjective	bitingly sarcastic; corrosive
censure	verb	to express strong formal disapproval
centralization	noun	the act of consolidating power under a central control
chafe	verb	become or make sore by or as if by rubbing
chafed	adjective	painful from having the skin abraded
charismatic	adjective	possessing an extraordinary ability to attract
cheapness	noun	a price below the standard price
checkup	noun	a thorough physical examination; includes a variety of tests depending on the age and sex and health of the person
chequer	verb	mark into squares or draw squares on; draw crossed lines on
chicanery	noun	the use of tricks to deceive someone
chilly	adjective	not characterized by emotion
chock	adverb	as completely as possible
cholestasis	noun	a condition in which little or no bile is secreted or the flow of bile into the digestive tract is obstructed
chomping	noun	the act of chewing noisily
circumference	noun	the size of something as given by the distance around it
circumflex	noun	a diacritical mark (^) placed above a vowel in some languages to indicate a special phonetic quality
circumspect	adjective	cautious; wary of risk and consequence
civics	noun	the social science of municipal affairs
clandestine	adjective	kept secret, usually because it is improper
clang	noun	a loud resonant repeating noise
claptrap	noun	pompous or pretentious talk or writing
clayey	adjective	resembling or containing clay
cleave	verb	separate or cut with a tool, such as a sharp instrument
cliffhanger	noun	a contest whose outcome is uncertain up to the very end
cloistered	adjective	of communal life sequestered from the world under religious vows
clotting	noun	the process of forming semisolid lumps in a liquid
coalesce	verb	to come together to form one whole
coaxing	adjective	pleasingly persuasive or intended to persuade
codex	noun	an official list of chemicals or medicines etc.
cogent	adjective	clear, logical, and convincing
colonization	noun	the act of colonizing; the establishment of colonies
colostomy	noun	a surgical operation that creates an opening from the colon to the surface of the body to function as an anus
commemorate	verb	celebrate by some ceremony or observation
complacent	adjective	smugly satisfied, and so unaware of danger
conciliatory	adjective	intended to placate or win goodwill
conciseness	noun	terseness and economy in writing and speaking achieved by expressing a great deal in just a few words
condone	verb	to accept or overlook behavior that is wrong
confirmatory	adjective	serving to support or corroborate
constellation	noun	an arrangement of parts or elements
contralateral	adjective	on or relating to the opposite side
contravention	noun	coming into conflict with
contusion	noun	an injury that doesn't break the skin but results in some discoloration
conundrum	noun	a confusing and difficult problem
convalescent	adjective	returning to health after illness or debility
conversant	adjective	well informed about or knowing thoroughly
coronation	noun	the ceremony of installing a new monarch
corroborate	verb	to confirm with supporting evidence
corrugated	adjective	shaped into alternating parallel grooves and ridges
corruptible	adjective	capable of being corrupted
cotillion	noun	a ball at which young ladies are presented to society
crabs	noun	infestation of the pubic hair by crab lice
craggy	adjective	having hills and crags
craze	verb	cause to go crazy; cause to lose one's mind
credulous	adjective	too ready to believe things; easily deceived
crinkled	adjective	uneven by virtue of having wrinkles or waves
croup	noun	a disease of infants and young children; harsh coughing and hoarseness and fever and difficult breathing
cryptic	adjective	mysterious in meaning; deliberately obscure
cuddle	verb	move or arrange oneself in a comfortable and cozy position
culpable	adjective	deserving blame
cursive	adjective	having successive letter joined together
cursory	adjective	hasty and not thorough
custodial	adjective	providing protective supervision; watching over or safeguarding
dandruff	noun	a condition in which white scales of dead skin are shed by the scalp
daunted	adjective	caused to show discomposure
dazzling	adjective	amazingly impressive; suggestive of the flashing of lightning
deafened	adjective	caused to hear poorly or not at all
dearth	noun	a scarcity or lack of something
debatable	adjective	open to doubt or debate
debauchery	noun	a wild gathering involving excessive drinking and promiscuity
debunk	verb	to expose the falseness of a claim or belief
deceptive	adjective	causing one to believe what is not true or fail to believe what is true
declarative	noun	a mood (grammatically unmarked) that represents the act or state as an objective fact
decorum	noun	behavior that is proper and in good taste
deference	noun	polite respect, and submission to another's judgment
deferment	noun	act of putting off to a future time
defiance	noun	intentionally contemptuous behavior or attitude
deforestation	noun	the state of being clear of trees
deleterious	adjective	causing harm or damage
delineate	verb	to describe or outline precisely
deluge	verb	fill quickly beyond capacity; as with a liquid
demeaning	adjective	causing awareness of your shortcomings
demeanour	noun	the way a person behaves toward other people
densification	noun	an increase in the density of something
densitometry	noun	measuring the optical density of a substance by shining light on it and measuring its transmission
depleted	adjective	no longer sufficient
depopulation	noun	the condition of having reduced numbers of inhabitants
deride	verb	to mock or ridicule with contempt
derogatory	adjective	expressive of low opinion
desiccated	adjective	thoroughly dried out
desolation	noun	the state of being decayed or destroyed
desperation	noun	a state in which all hope is lost or absent
destitute	adjective	poor enough to need help from others
desultory	adjective	lacking a plan or purpose; jumping from one thing to another
detachable	adjective	designed to be unfastened or disconnected without damage
detente	noun	the easing of tensions or strained relations
deter	verb	to discourage someone from acting, usually by instilling doubt
deterrence	noun	a negative motivational influence
detested	adjective	treated with dislike or contempt
devious	adjective	indirect in departing from the accepted or proper way; misleading
dialect	noun	the usage or vocabulary that is characteristic of a specific group of people
diatribe	noun	a bitter, forceful verbal attack
didactic	adjective	intended to teach, often in a heavy-handed moral way
diffident	adjective	shy and lacking self-confidence
digestibility	noun	the property of being easy to digest
digitalization	noun	the administration of digitalis for the treatment of certain heart disorders
digress	verb	to stray from the main subject
dilatory	adjective	slow to act; causing delay
dinge	verb	make a dent or impression in
dingy	adjective	thickly covered with ingrained dirt or soot
dirge	noun	a song or hymn of mourning composed or performed as a memorial to a dead person
discoloration	noun	a soiled or discolored appearance
discontented	adjective	showing or experiencing dissatisfaction or restless longing
discrepant	adjective	not compatible with other facts
disenchantment	noun	freeing from false belief or illusions
disgusted	adjective	having a strong distaste from surfeit
disheartened	adjective	made less hopeful or enthusiastic
disparage	verb	to belittle or speak of slightingly
disparate	adjective	essentially different and unrelated
dispel	verb	force to go away; used both with concrete and metaphoric meanings
dissemble	verb	to hide one's true motives or feelings
distinctness	noun	the quality of being sharp and clear
dizzy	adjective	having or causing a whirling sensation; liable to falling
docile	adjective	easily managed and willing to be taught
dogging	adjective	relentless and indefatigable in pursuit or as if in pursuit
dogmatic	adjective	asserting opinions as if they were beyond question
dower	verb	furnish with an endowment
dramatization	noun	conversion into dramatic form
drool	verb	be envious, desirous, eager for, or extremely happy about something
dubious	adjective	doubtful; questionable in quality or truth
dyslexia	noun	impaired ability to learn to read
ebullient	adjective	overflowing with enthusiasm and energy
eccentricity	noun	strange and unconventional behavior
ecclesiology	noun	the branch of theology concerned with the nature and the constitution and the functions of a church
eclectic	adjective	drawing on a wide and varied range of sources
econometrics	noun	the application of mathematics and statistics to the study of economic and financial data
efficacy	noun	the power to produce the intended result
egoistic	adjective	limited to or caring only about yourself and your own needs
egregious	adjective	outstandingly bad; shockingly wrong
elaboration	noun	addition of extra material or illustration or clarifying detail
eldritch	adjective	suggesting the operation of supernatural influences
electrifying	adjective	causing a surge of emotion or excitement
electrostatics	noun	the branch of physics that deals with static electricity
elicit	verb	to draw out a response or reaction
elope	verb	run away secretly with one's beloved
eloquent	adjective	fluent and persuasive in speech or writing
elucidate	verb	to make clear by explaining
embargo	verb	ban the publication of (documents), as for security or copyright reasons
embed	verb	fix or set securely or deeply
embroiled	adjective	deeply involved especially in something complicated
emcee	verb	act as a master of ceremonies
empathetic	adjective	showing empathy or ready comprehension of others' states
emulate	verb	to imitate, especially in order to match or surpass
encompass	verb	include in scope; include as part of something broader; have as one's sphere or territory
encrypt	verb	convert ordinary language into code
endodontics	noun	the branch of dentistry dealing with diseases of the dental pulp
enervate	verb	to drain of energy and vitality
engender	verb	to give rise to; to bring about
engorged	adjective	overfull as with blood
engrossment	noun	complete attention; intense mental effort
enigma	noun	a person or thing that is mysterious and hard to understand
enmity	noun	a state of deep-seated ill-will
enormity	noun	the quality of being outrageous
entailment	noun	something that is inferred
entreaty	noun	earnest or urgent request
ephemeral	adjective	lasting a very short time
epitaph	noun	an inscription on a tombstone or monument in memory of the person buried there
epitomize	verb	embody the essential characteristics of or be a typical example of
equanimity	noun	calmness and composure under strain
errand	noun	a short trip that is taken in the performance of a necessary task or mission
erudite	adjective	having or showing deep scholarly knowledge
esoteric	adjective	understood only by a small group with special knowledge
estrus	noun	applies to nonhuman mammals: a state or period of heightened sexual arousal and activity
eulogy	noun	a speech of high praise, especially for someone who has died
euphemism	noun	a mild word substituted for one thought harsh or blunt
evacuate	verb	move out of an unsafe location into safety
exacerbate	verb	to make a bad situation worse
exemplar	noun	something to be imitated
exemplary	adjective	serving as a desirable model; outstandingly good
exemplifying	adjective	clarifying by use of examples
exhaustive	adjective	thorough and complete, leaving nothing out
exogenous	adjective	derived or originating externally
exonerate	verb	to clear of blame or accusation
expelling	noun	any of several bodily processes by which substances go out of the body
expository	adjective	serving to expound or set forth
extenuating	adjective	partially excusing or justifying
exterminated	adjective	destroyed completely
extravagant	adjective	unrestrained, especially with regard to feelings
facetious	adjective	joking about something that deserves to be taken seriously
fallacious	adjective	based on faulty reasoning; misleading
fallow	adjective	left unplowed and unseeded during a growing season
fanned	adjective	especially spread in a fan shape
fastened	adjective	firmly closed or secured
fastidious	adjective	very attentive to detail; hard to please
fatness	noun	excess bodily weight
fervent	adjective	showing intense and passionate feeling
fester	verb	ripen and generate pus
festschrift	noun	a collection of writings published in honor of a scholar
fetching	adjective	very attractive; capturing interest
fibrous	adjective	having or resembling fibers especially fibers used in making cordage such as those of jute
fickle	adjective	changing loyalty or affection without good reason
fidgety	adjective	nervous and unable to relax
flaxen	adjective	of hair color; pale yellowish to yellowish brown
flexion	noun	the state of being flexed
flout	verb	to openly disregard a rule or convention
foolhardy	adjective	marked by defiant disregard for danger or consequences
foolishness	noun	the trait of acting stupidly or rashly
foreground	noun	the part of a scene that is near the viewer
foreshadowing	adjective	indistinctly prophetic
fortify	verb	make strong or stronger
fortuitous	adjective	happening by chance, often luckily
frayed	adjective	worn away or tattered along the edges
frizzy	adjective	in small tight curls
frothing	adjective	producing or covered with lathery sweat or saliva from exhaustion or disease
frugal	adjective	sparing with money or resources
fulfilment	noun	a feeling of satisfaction at having achieved your desires
furtive	adjective	done quietly to avoid being noticed
futile	adjective	pointless; incapable of producing any result
galvanizing	adjective	affected by emotion as if by electricity; thrilling
gargantuan	adjective	of great mass; huge and bulky
garrulous	adjective	excessively talkative about trivial things
gasconade	noun	an instance of boastful talk
gasification	noun	the process of changing into gas
gayness	noun	a sexual attraction to (or sexual relations with) persons of the same sex
germane	adjective	genuinely relevant to the matter at hand
germinal	adjective	containing seeds of later development
gerontology	noun	the branch of medical science that deals with diseases and problems specific to old people
gestalt	noun	a configuration or pattern of elements so unified as a whole that it cannot be described merely as a sum of its parts
gibberish	noun	unintelligible talking
gilded	adjective	having the deep slightly brownish color of gold
glaucous	adjective	having a frosted look from a powdery coating, as on plants
glimmering	noun	a slight suggestion or vague understanding
googly	noun	a cricket ball bowled as if to break one way that actually breaks in the opposite way
graciousness	noun	excellence of manners or social conduct
granular	adjective	composed of or covered with particles resembling meal in texture or consistency
grapevine	noun	gossip spread by spoken communication
grapple	verb	succeed in doing, achieving, or producing (something) with the limited or inadequate means available
graven	adjective	cut into a desired shape
gregarious	adjective	sociable; fond of company
grinning	noun	a facial expression characterized by turning up the corners of the mouth; usually shows pleasure or amusement
gripes	noun	acute abdominal pain
grumpy	adjective	annoyed and irritable
guile	noun	cunning used to deceive
habitability	noun	suitability for living in or on
hackneyed	adjective	worn out by overuse; unoriginal
handmaid	noun	in a subordinate position
handsewn	adjective	sewn by hand rather than machine
hankering	noun	a yearning for something or to do something
harangue	noun	a loud bombastic declamation expressed with strong emotion
harbinger	noun	a sign of something about to happen
harried	adjective	troubled persistently especially with petty annoyances
haughty	adjective	arrogantly superior toward others
heartening	adjective	cheerfully encouraging
hedonism	noun	the pursuit of pleasure as a matter of ethical principle
helplessness	noun	powerlessness revealed by an inability to act
hepatoma	noun	carcinoma of the liver
heresy	noun	a belief that contradicts accepted doctrine
hermetic	adjective	completely sealed; completely airtight
hesitating	adjective	lacking decisiveness of character; unable to act or decide quickly or firmly
heterosexuality	noun	a sexual attraction to (or sexual relations with) persons of the opposite sex
hiatus	noun	a pause or gap in continuity
highbrow	adjective	highly cultured or educated
hoary	adjective	showing characteristics of age, especially having grey or white hair
hubris	noun	excessive pride that invites downfall
huffing	noun	an act of forcible exhalation
hulking	adjective	of great size and bulk
hunch	verb	round one's back by bending forward and drawing the shoulders forward
hunched	adjective	having the back and shoulders rounded; not erect
hybridize	verb	breed animals or plants using parents of different races and varieties
hydrotherapy	noun	the internal and external use of water in the treatment of disease
hygienic	adjective	tending to promote or preserve health
hyperbolic	adjective	enlarged beyond truth or reasonableness
hyperglycemia	noun	abnormally high blood sugar usually associated with diabetes
hypospadias	noun	an abnormal condition in males in which the urethra opens on the under surface of the penis
iconoclast	noun	a person who attacks cherished beliefs or institutions
ideograph	noun	a graphic character that indicates the meaning of a thing without indicating the sounds used to say it
idiosyncrasy	noun	a peculiar habit or feature of one person
illiteracy	noun	ignorance resulting from not reading
illogical	adjective	lacking in correct logical relation
illuminating	adjective	tending to increase knowledge or dissipate ignorance
imbroglio	noun	an intricate and confusing interpersonal or political situation
immunogenic	adjective	possessing the ability to elicit an immune response
immutable	adjective	unchanging and unable to be changed
impair	verb	make worse or less effective
impartiality	noun	an inclination to weigh both views or opinions equally
impassable	adjective	incapable of being passed
impatience	noun	a lack of patience; irritation with anything that causes delay
impeccable	adjective	flawless; without any fault
impermanent	adjective	not permanent; not lasting
impersonation	noun	a representation of a person that is exaggerated for comic effect
impetuous	adjective	acting quickly without thought or care
implacable	adjective	impossible to appease or soften
impudent	adjective	marked by casual disrespect
inadvertent	adjective	unintentional; done without noticing
inaudible	adjective	impossible to hear; imperceptible by the ear
incase	verb	enclose in, or as if in, a case
incensed	adjective	angered at something unjust or wrong
incessant	adjective	continuing without pause
incisive	adjective	showing sharp, clear thinking
incompleteness	noun	the state of being crude and incomplete and imperfect
incongruous	adjective	out of place; not in harmony with its surroundings
inconvenient	adjective	not suited to your comfort, purpose or needs
incubate	verb	grow under conditions that promote development
incursion	noun	the act of entering some territory or domain
indefensible	adjective	incapable of being defended or justified
indefinable	adjective	not capable of being precisely or readily described; not easily put into words
indifference	noun	unbiased impartial unconcern
indigenous	adjective	originating naturally in a particular place
indolent	adjective	habitually idle; averse to effort
indomitable	adjective	impossible to subdue
ineffable	adjective	too great to be put into words
inequity	noun	injustice by virtue of not conforming with rules or standards
inert	adjective	unable to move or resist motion
inexorable	adjective	impossible to stop or persuade
infarction	noun	localized necrosis resulting from obstruction of the blood supply
infective	adjective	able to cause disease
infertile	adjective	incapable of reproducing
infraction	noun	a crime less serious than a felony
ingenuous	adjective	innocent and unguarded; frank
ingrown	adjective	growing abnormally into the flesh
inhibitory	adjective	restrictive of action
injurious	adjective	harmful to living things
innocuous	adjective	harmless; unlikely to offend
inshore	adjective	coming from the sea toward the land
insidious	adjective	spreading harm gradually and unnoticed
insipid	adjective	lacking flavour, interest, or vigour
insolation	noun	sudden prostration due to exposure to the sun or excessive heat
insolent	adjective	marked by casual disrespect
instantiation	noun	a representation of an idea in the form of an instance of it
instillation	noun	the introduction of a liquid (by pouring or injection) drop by drop
insulting	adjective	expressing extreme contempt
intermediation	noun	the act of intervening for the purpose of bringing about a settlement
internationale	noun	a revolutionary socialist anthem
intimidated	adjective	made timid or fearful as by threats
intoxication	noun	the physiological state produced by a poison or other toxic substance
intractability	noun	the trait of being hard to influence or control
intransigent	adjective	refusing to compromise
intrepid	adjective	fearless in the face of danger
inundate	verb	to overwhelm, or to flood
inure	verb	cause to accept or become hardened to; habituate
invective	noun	abusive or venomous language used to express blame or censure or bitter deep-seated ill will
invertible	adjective	having an additive or multiplicative inverse
investiture	noun	the ceremony of installing a new monarch
invincible	adjective	incapable of being overcome or subdued
inviolable	adjective	incapable of being transgressed or dishonored
invulnerable	adjective	immune to attack; impregnable
irascible	adjective	easily provoked to anger
irate	adjective	feeling or showing extreme anger
ironclad	adjective	sheathed in iron plates for protection
irreparable	adjective	impossible to repair, rectify, or amend
isomerization	noun	the conversion of a compound into an isomer of itself
jinxed	adjective	causing or accompanied by misfortune
judicious	adjective	showing good judgment and sense
juxtapose	verb	to place side by side for contrast
juxtaposed	adjective	placed side by side often for comparison
kaleidoscopic	adjective	continually shifting or rapidly changing
kannada	noun	a Dravidian language spoken in southern India
knack	noun	a special way of doing something
knockout	adjective	very strong or vigorous
kudos	noun	an expression of approval and commendation
kyphosis	noun	an abnormal backward curve to the vertebral column
lacklustre	adjective	lacking brilliance or vitality
laconic	adjective	using very few words
ladin	noun	a Rhaeto-Romance dialect of Romansh spoken in southeastern Switzerland
lamenting	adjective	vocally expressing grief or sorrow or resembling such expression
languid	adjective	lacking energy; pleasantly slow
languor	noun	a relaxed comfortable feeling
lanky	adjective	tall and thin and having long slender limbs
laud	verb	to praise highly
laxative	adjective	stimulating evacuation of feces
leafy	adjective	having or covered with leaves
leaky	adjective	permitting the unwanted passage of fluids or gases
lethargic	adjective	sluggish and lacking energy
levity	noun	lightness of manner, especially when seriousness is expected
libertine	adjective	unrestrained by convention or morality
liege	adjective	owing or owed feudal allegiance and service
likening	noun	the act of comparing similarities
lineal	adjective	in a straight unbroken line of descent from parent to child
lipped	adjective	having a lip or lips
lithography	noun	a method of planographic printing from a metal or stone surface
loamy	adjective	consisting of or having the character of loam
loath	adjective	unwillingness to do something contrary to your custom
loathing	noun	hate coupled with disgust
loathsome	adjective	causing or able to cause nausea
lofty	adjective	of high moral or intellectual value; elevated in nature or style
loquacious	adjective	very talkative
lossy	adjective	characterized by or causing dissipation of energy
lowly	adjective	low or inferior in station or quality
lucid	adjective	clearly expressed, or clear-headed
luminescent	adjective	emitting light not caused by heat
lunge	verb	make a thrusting forward movement
magnanimous	adjective	generous and forgiving, especially toward a rival
mahjong	noun	Chinese game played by 4 people with 144 tiles
maimed	adjective	having a part of the body crippled or disabled
malevolent	adjective	wishing harm to others
malice	noun	feeling a need to see others suffer
malleable	adjective	easily shaped, or easily influenced
maneuver	verb	direct the course; determine the direction of travelling
manly	adjective	possessing qualities befitting a man
manoeuvre	verb	act in order to achieve a certain goal
masochism	noun	sexual pleasure obtained from receiving punishment
matinee	noun	a theatrical performance held during the daytime
maximisation	noun	the act of raising to the highest possible point or condition or position
mediocre	adjective	moderate to inferior in quality
mediocrity	noun	ordinariness as a consequence of being average and not outstanding
mellowed	adjective	having a full and pleasing flavor through proper aging
melodious	adjective	having a musical sound; especially a pleasing tune
mendacity	noun	the tendency to be untruthful
menstruation	noun	the monthly discharge of blood from the uterus of nonpregnant women from puberty to menopause
merciless	adjective	having or showing no mercy
meticulous	adjective	showing great care over every detail
metrical	adjective	based on the meter as a standard of measurement
miscegenation	noun	reproduction by parents of different races
misguided	adjective	poorly conceived or thought out
mitigate	verb	to make something bad less severe
mobilisation	noun	act of marshaling and organizing and making ready for use or action
mollify	verb	to soothe the anger of
momentary	adjective	lasting for a markedly brief time
monopolize	verb	have and control fully and exclusively
moony	adjective	lighted by moonlight
moralizing	noun	indulgence in moral pronouncements; the exposition (often superficially) of a particular moral code
morose	adjective	gloomy and sullen
motility	noun	ability to move spontaneously and independently
mountainous	adjective	having hills and crags
multifaceted	adjective	having many aspects or qualities
multiplicity	noun	the property of being multiple
mummification	noun	a condition resembling that of a mummy
mundane	adjective	ordinary and dull; of the everyday world
munificent	adjective	extremely generous
murmuring	adjective	making a low continuous indistinct sound
mutilation	noun	an injury that causes disfigurement or that deprives you of a limb or other important body part
myoclonus	noun	a clonic spasm of a muscle or muscle group
myriad	noun	a countless number of things
mystified	adjective	totally perplexed and mixed up
mystifying	adjective	of an obscure nature
nadir	noun	an extreme state of adversity; the lowest point of anything
narcolepsy	noun	a sleep disorder characterized by sudden and uncontrollable episodes of deep sleep
navigability	noun	the quality of being suitable for the passage of a ship or aircraft
nebulous	adjective	vague and ill-defined
nefarious	adjective	wicked; criminal in intent
negate	verb	be in contradiction with
neophyte	noun	a beginner at something
neoplasia	noun	the pathological process that results in the formation and growth of a tumor
neuroticism	noun	a mental or personality disturbance not attributable to any known neurological or organic dysfunction
neutropenia	noun	leukopenia in which the decrease is primarily in number of neutrophils
nippy	adjective	a sharp biting taste
nociceptive	adjective	caused by or in response to pain
nonchalant	adjective	calmly unconcerned
nonconformist	adjective	not conforming to some norm or socially approved pattern of behavior or thought
nonconformity	noun	lack of harmony or correspondence
nonexistent	adjective	not having existence or being or actuality
nonionic	adjective	not converted into ions
nonsteroidal	adjective	not steroidal or not having the effects of steroid hormones
nontaxable	adjective	not subject to taxation
nuance	noun	a subtle difference in meaning or feeling
nudism	noun	going without clothes as a social practice
nullified	adjective	deprived of legal force
nynorsk	noun	one of two official languages of Norway; based on rural dialects
oaken	adjective	consisting of or made of wood of the oak tree
obdurate	adjective	stubbornly refusing to change an opinion
obfuscate	verb	to make something unclear on purpose
obliteration	noun	destruction by annihilating something
oblivious	adjective	entirely unaware of what is happening
obsequious	adjective	excessively eager to please or obey
obsolete	adjective	no longer in use; out of date
obstinacy	noun	the trait of being difficult to handle or overcome
obstinate	adjective	stubbornly refusing to change course
obstruct	verb	hinder or prevent the progress or accomplishment of
oedema	noun	swelling from excessive accumulation of watery fluid in cells, tissues, or serous cavities
ominous	adjective	suggesting that something bad is coming
onshore	adjective	coming from the sea toward the land
opaque	adjective	impossible to see through, or hard to understand
opinionated	adjective	obstinate in your opinions
opulent	adjective	luxurious and costly
ordeal	noun	a severe or trying experience
orientalism	noun	the scholarly knowledge of Asian cultures and languages and people
orienting	adjective	positioning with respect to a reference system or determining your bearings physically or intellectually
orphaned	adjective	deprived of parents by death or desertion
oscillating	adjective	having periodic vibrations
ostentatious	adjective	designed to impress; showy
ostracize	verb	to exclude someone from a group
otitis	noun	inflammation of the ear
otology	noun	the branch of medicine concerned with the ear
ousting	noun	the act of ejecting someone or forcing them out
outlandish	adjective	conspicuously or grossly unconventional or unusual
ovate	adjective	of a leaf shape; egg-shaped with the broader end at the base
overblown	adjective	puffed up with vanity
overstuffed	adjective	upholstered thickly and deeply
oxidize	verb	enter into a combination with oxygen or become converted into an oxide
oxygenation	noun	the process of providing or combining or treating with oxygen
palliation	noun	easing the severity of a pain or a disease without removing the cause
palliative	adjective	moderating pain or sorrow by making it easier to bear
palpable	adjective	so intense it feels almost physical
paragon	noun	a perfect example of a quality
paranasal	adjective	adjacent to the nasal cavities
pathogenesis	noun	the origination and development of a disease
pathogenic	adjective	able to cause disease
patois	noun	a characteristic language of a particular group
paucity	noun	a shortage; too small an amount
pedantic	adjective	overly concerned with minor rules and details
peeved	adjective	aroused to impatience or anger
penchant	noun	a strong liking for something
penetrate	verb	pass into or through, often by overcoming resistance
penetrative	adjective	having or demonstrating ability to recognize or draw fine distinctions
pentathlon	noun	an athletic contest consisting of five different events
perceivable	adjective	capable of being perceived especially by sight or hearing
perfunctory	adjective	done without care, merely as a duty
peristalsis	noun	the process of wavelike muscle contractions of the alimentary tract that moves food along
permeate	verb	spread or diffuse through
pernicious	adjective	causing harm in a gradual, hidden way
perplex	verb	be a mystery or bewildering to
perspicacious	adjective	having keen insight, especially into people
persuasive	adjective	intended or having the power to induce action or belief
pertinent	adjective	directly relevant
perturbing	adjective	causing distress or worry or anxiety
pertussis	noun	a disease of the respiratory mucous membrane
pervasive	adjective	spreading widely through every part
perversity	noun	deliberate and stubborn unruliness and resistance to guidance or discipline
pervious	adjective	admitting of passage or entrance
pessimism	noun	the feeling that things will turn out badly
pestered	adjective	troubled persistently especially with petty annoyances
petrology	noun	the branch of geology that studies rocks: their origin and formation and mineral composition and classification
phoney	adjective	fraudulent; having a misleading appearance
phony	adjective	fraudulent; having a misleading appearance
photometry	noun	measurement of the properties of light
pigeonhole	verb	place into a small compartment
pimple	noun	a small inflamed elevation of the skin; a pustule or papule; common symptom in acne
pious	adjective	having or showing or expressing reverence for a deity
pithy	adjective	concise and full of meaning
pizzazz	noun	the activeness of an energetic personality
placate	verb	to calm someone's anger
plaudits	noun	enthusiastic approval
plausible	adjective	seeming reasonable, though possibly untrue
plough	verb	move in a way resembling that of a plow cutting into or going through the soil
plundered	adjective	wrongfully emptied or stripped of anything of value
poaching	noun	cooking in simmering liquid
polygamy	noun	the condition or practice of having more than one spouse at a time
pompous	adjective	puffed up with vanity
popery	noun	offensive terms for the practices and rituals of the Roman Catholic Church
popularization	noun	an interpretation that easily understandable and acceptable
postpartum	adjective	occurring immediately after birth
powerlessness	noun	the quality of lacking strength or power; being weak and feeble
pragmatic	adjective	dealing with things practically rather than ideally
precarious	adjective	unstable; dependent on chance
preclude	verb	to make impossible in advance
preconceived	adjective	formed beforehand; especially without evidence or through prejudice
predilection	noun	a natural preference for something
presbyopia	noun	a reduced ability to focus on near objects caused by loss of elasticity of the crystalline lens after age 45
prescient	adjective	knowing what will happen before it does
priapism	noun	condition in which the penis is continually erect; usually painful and seldom with sexual arousal
prick	verb	make a small hole into, as with a needle or a thorn
prideful	adjective	having or showing arrogant superiority to and disdain of those one views as unworthy
primal	adjective	serving as an essential component
prissy	adjective	exaggeratedly proper
pristine	adjective	in its original, unspoiled condition
prodigal	adjective	wastefully extravagant
prolapse	verb	slip or fall out of place, as of body parts
prolific	adjective	producing a great deal
prologue	noun	an introduction to a play
promenade	verb	march in a procession
propensity	noun	a natural inclination to behave a certain way
prosaic	adjective	plain and unimaginative
prosody	noun	the patterns of stress and intonation in a language
prostatectomy	noun	surgical removal of part or all of the prostate gland
prostrate	adjective	stretched out and lying at full length along the ground
provable	adjective	capable of being demonstrated or proved
providential	adjective	peculiarly fortunate or appropriate; as if by divine intervention
provincial	adjective	narrow in outlook; of the regions rather than the capital
prudent	adjective	acting with care for the future
psychoactive	adjective	affecting the mind or mood or other mental processes
ptosis	noun	drooping of the upper eyelid caused by muscle paralysis and weakness
publicizing	noun	the business of drawing public attention to goods and services
puffed	adjective	gathered for protruding fullness
pugnacious	adjective	eager to argue or fight
pukka	adjective	absolutely first class and genuine
purview	noun	the range of interest or activity that can be anticipated
putsch	noun	a sudden and decisive change of government illegally or by force
qiang	noun	the Tibeto-Burman language spoken in Sichuan
quack	adjective	medically unqualified
quadratic	noun	an equation in which the highest power of an unknown quantity is a square
queasy	adjective	causing or able to cause nausea
quell	verb	to put an end to, usually by force
querulous	adjective	habitually complaining
quiescent	adjective	inactive or at rest for the time being
quintessential	adjective	representing the purest example of its kind
quixotic	adjective	idealistic to the point of being impractical
rambunctious	adjective	noisy and lacking in restraint or discipline
rampant	adjective	unrestrained and violent
rancor	noun	long-held bitterness or resentment
ransacked	adjective	wrongfully emptied or stripped of anything of value
rationalization	noun	the cognitive process of making something seem consistent with or based on reason
razorback	adjective	having a sharp narrow back
reactionary	adjective	opposed to political or social liberalism or reform
realisation	noun	a musical composition that has been completed or enriched by someone other than the composer
reassign	verb	transfer somebody to a different position or location of work
rebind	verb	provide with a new binding
rebroadcast	noun	a broadcast that repeated at a later time
rebuke	verb	to criticize sharply
recalcitrant	adjective	stubbornly resisting authority
recapture	noun	a legal seizure by the government of profits beyond a fixed amount
receding	noun	a slow or gradual disappearance
reciprocal	adjective	given and received in equal measure
recluse	adjective	withdrawn from society; seeking solitude
recompense	verb	make amends for; pay compensation for
reconstructed	adjective	adapted to social or economic change
redress	verb	make reparations or amends for
redundant	adjective	more than is needed; superfluous
reentry	noun	the act of entering again
reflux	noun	an abnormal backward flow of body fluids
refractory	adjective	not responding to treatment
refute	verb	to prove a claim wrong with evidence
regenerate	adjective	reformed spiritually or morally
reissue	noun	a publication (such as a book) that is reprinted without changes or editing and offered again for sale
relegate	verb	to consign to a lower rank or position
relegation	noun	authorizing subordinates to make certain decisions
remission	noun	an abatement in intensity or degree
reorder	verb	assign a new order to
repot	verb	put in a new, usually larger, pot
reproach	verb	express criticism towards
repudiate	verb	to reject or disown formally
reschedule	verb	assign a new time and place for an event
resilient	adjective	able to recover quickly from difficulty
resuscitate	verb	cause to regain consciousness
retaliate	verb	take revenge for a perceived wrong
retard	verb	cause to move more slowly or operate at a slower rate
rethink	noun	thinking again about a choice previously made
reticent	adjective	unwilling to say much
revel	noun	unrestrained merrymaking
revere	verb	love unquestioningly and uncritically or to excess; venerate as an idol
reversibility	noun	the quality of being reversible in either direction
revert	verb	go back to a previous state
revising	noun	editing that involves writing something again
revitalizing	adjective	tending to impart new life and vigor to
rhetoric	noun	the art of persuasive speech, or language empty of substance
rhythmical	adjective	recurring with measured regularity
riddled	adjective	damaged throughout by numerous perforations or holes
rioting	noun	a state of disorder involving group violence
ripping	adjective	resembling a sound of violent tearing as of something ripped apart or lightning splitting a tree
riskiness	noun	a state of danger involving risk
roaring	adjective	very lively and profitable
rococo	adjective	having excessive asymmetrical ornamentation
roughness	noun	a texture of a surface or edge that is not smooth but is irregular and uneven
ruckus	noun	the act of making a noisy disturbance
rudimentary	adjective	basic and undeveloped
rumbling	adjective	continuous full and low-pitched throbbing sound
ruminate	verb	to think something over at length
rummy	adjective	beyond or deviating from the usual or expected
rustle	verb	make a dry crackling sound
sacredness	noun	the quality of being sacred
sadistic	adjective	deriving pleasure or sexual gratification from inflicting pain on another
sagacious	adjective	showing deep wisdom and good judgment
salient	adjective	most noticeable or important
salutary	adjective	tending to promote physical well-being; beneficial to health
sameness	noun	the quality of being alike
sanctioned	adjective	conforming to orthodox or recognized rules
sanguine	adjective	cheerfully optimistic, especially in bad circumstances
sarcastic	adjective	expressing or expressive of ridicule that wounds
satanic	adjective	extremely evil or cruel; expressive of cruelty or befitting hell
satanism	noun	a belief in and reverence for devils
satiny	adjective	having a smooth, gleaming surface reflecting light
satiric	adjective	exposing human folly to ridicule
satisfiable	adjective	capable of being sated
saucy	adjective	characterized by a lightly pert and exuberant quality
savagery	noun	the property of being untamed and ferocious
scoured	adjective	worn away as by water or ice or wind
scourge	verb	punish severely; excoriate
screwy	adjective	not behaving normally
scrupulous	adjective	careful to do what is right, down to the detail
scrutinise	verb	to look at critically or searchingly, or in minute detail
scrutinize	verb	to examine closely and critically
scurrying	adjective	moving with great haste
seclusion	noun	the quality of being secluded from the presence or view of others
sedentary	adjective	requiring sitting or little activity
seductive	adjective	tending to entice into a desired action or state
semitic	noun	a major branch of the Afro-Asiatic language family
sensibility	noun	mental responsiveness and awareness
servile	adjective	excessively submissive
sesotho	noun	the dialect of Sotho spoken by the Basotho; an official language of Lesotho
shackled	adjective	bound by chains fastened around the ankles
shakeup	noun	the imposition of a new organization; organizing differently
shambles	noun	a condition of great disorder
sharpness	noun	a quick and penetrating intelligence
shrinkage	noun	process or result of becoming less or smaller
shuddering	adjective	shaking convulsively or violently
sifting	noun	the act of separating grain from chaff
sightedness	noun	normal use of the faculty of vision
sinning	adjective	transgressing a moral or divine law
skittles	noun	a bowling game that is played by rolling a bowling ball down a bowling alley at a target of nine wooden pins
slithering	adjective	moving as on a slippery surface
sloppy	adjective	lacking neatness or order
sloth	noun	a disinclination to work or exert yourself
slothful	adjective	disinclined to work or exertion
slump	verb	assume a drooping posture or carriage
smelt	verb	extract (metals) by heating
smouldering	adjective	showing scarcely suppressed anger
smutty	adjective	characterized by obscenity
snoopy	adjective	offensively curious or inquisitive
snooze	verb	sleep lightly or for a short period of time
socialized	adjective	under group or government control
socioeconomic	adjective	involving social as well as economic factors
soldering	noun	fastening firmly together
soporific	adjective	tending to induce sleep
sorption	noun	the process in which one substance takes up or holds another
sorrel	adjective	of a light brownish color
spasmodic	adjective	affected by involuntary jerky muscular contractions; resembling a spasm
specious	adjective	seeming right but actually false
spiritualism	noun	any doctrine that asserts the separate existence of God
sporadic	adjective	occurring at irregular intervals
spurious	adjective	not genuine; based on false reasoning
spurned	adjective	rebuffed (by a lover) without warning
squander	verb	to waste something valuable
stabilise	verb	support or hold steady and make steadfast, with or as if with a brace
staccato	adverb	separating the notes; in music
stagnant	adjective	not flowing or developing
staunch	adjective	loyal and firm in commitment
stead	noun	the post or function properly or customarily occupied or served by another
stenosis	noun	abnormal narrowing of a bodily canal or passageway
stifled	adjective	held in check with difficulty
stink	verb	be extremely bad in quality or in one's performance
stinky	adjective	having an unpleasant smell
stint	verb	subsist on a meager allowance
stocky	adjective	having a short and solid form or stature
stoic	adjective	enduring pain or hardship without complaint
straitjacket	noun	anything immaterial that severely hinders or confines
stricken	adjective	grievously affected especially by disease
strident	adjective	loud and harsh; forcefully insistent
stupefied	adjective	as if struck dumb with astonishment and surprise
subconscious	adjective	just below the level of consciousness
subjugate	verb	to bring under domination
subservient	adjective	compliant and obedient to authority
subsumption	noun	the premise of a syllogism that contains the minor term
succinct	adjective	expressed clearly in few words
succor	verb	help in a difficult situation
suffocation	noun	killing by depriving of oxygen
sundanese	noun	the Indonesian language spoken on West Java
superfluous	adjective	more than is needed; unnecessary
supplant	verb	to take the place of something displaced
surreptitious	adjective	done secretly to escape notice
swagger	verb	to walk with a lofty proud gait, often in an attempt to impress others
swanky	adjective	imposingly fashionable and elegant
swart	adjective	naturally having skin of a dark color
swashbuckling	adjective	flamboyantly adventurous
swilling	noun	the drinking of large mouthfuls rapidly
swish	adjective	elegant and fashionable
sycophant	noun	a person who flatters the powerful for advantage
synchronisation	noun	the relation that exists when things occur at the same time
syncope	noun	a spontaneous loss of consciousness caused by insufficient blood to the brain
synonymy	noun	the semantic relation that holds between two words that can (in a given context) express the same meaning
taciturn	adjective	saying little by nature
tangential	adjective	only loosely connected to the subject
tangerine	adjective	of a strong reddish orange color
tattered	adjective	worn to shreds; or wearing torn or ragged clothing
tedious	adjective	so lacking in interest as to cause mental weariness
temerity	noun	boldness that borders on recklessness
tenacious	adjective	holding firmly; persistent
tenderness	noun	a tendency to express warm and affectionate feeling
tentative	adjective	provisional; done without confidence
tenuous	adjective	very weak or slight
terrify	verb	fill with terror; frighten greatly
terse	adjective	brief to the point of curtness
tewkesbury	noun	the final battle of the War of the Roses in 1471 in which Edward IV defeated the Lancastrians
thawed	adjective	no longer frozen solid
theoretic	adjective	concerned primarily with theories or hypotheses rather than practical considerations
theosophy	noun	a system of belief based on mystical insight into the nature of God and the soul
thrifty	adjective	careful and diligent in the use of resources
throttling	noun	the act of suffocating (someone) by constricting the windpipe
thwart	verb	to prevent someone from achieving something
timorous	adjective	nervous and easily frightened
tingling	adjective	exciting by touching lightly so as to cause laughter or twitching movements
titillating	adjective	pleasantly and superficially exciting
torpor	noun	sluggish inactivity
tortuous	adjective	highly complex or intricate and occasionally devious
totalitarian	adjective	characterized by a government in which the political authority exercises absolute and centralized control
tractable	adjective	easy to control or manage
transient	adjective	lasting only a short time
transmissible	adjective	capable of being transmitted by infection
tremble	verb	move or jerk quickly and involuntarily up and down or sideways
trepidation	noun	anxiety about what is to come
trite	adjective	dulled by overuse; lacking freshness
trope	noun	language used in a figurative or nonliteral sense
truculent	adjective	aggressively defiant
truncate	adjective	terminating abruptly by having or as if having an end or point cut off
truncated	adjective	cut short in duration
trustworthiness	noun	the trait of deserving trust and confidence
tumbling	noun	the gymnastic moves of an acrobat
turbid	adjective	clouded as with sediment
turkic	noun	a subfamily of Altaic languages
twaddle	verb	speak (about unimportant matters) rapidly and incessantly
twinkling	adjective	shining intermittently with a sparkling light
ubiquitous	adjective	present everywhere at once
unary	adjective	consisting of or involving a single element or component
uncaring	adjective	lacking affection or warm feeling
unceasing	adjective	continuing forever or indefinitely
unchanging	adjective	conforming to the same principles or course of action over time
unconsolidated	adjective	loose and unstratified
uncritical	adjective	marked by disregard for critical standards or procedures
unction	noun	excessive but superficial compliments given with affected charm
underprivileged	adjective	lacking the rights and advantages of other members of society
undeserved	adjective	not deserved or earned
undiminished	adjective	not lessened or diminished
undress	noun	partial or complete nakedness
unemotional	adjective	unsusceptible to or destitute of or showing no emotion
unequalled	adjective	radically distinctive and without equal
unequivocal	adjective	leaving no doubt; admitting one meaning only
unfaithful	adjective	not true to duty or obligation or promises
unfilled	adjective	of purchase orders that have not been filled
unformed	adjective	not having form or shape
unfriendly	adjective	not easy to understand or use
unhelpful	adjective	providing no assistance
unicameral	adjective	composed of one legislative body
unilateral	adjective	involving only one part or side
unmanageable	adjective	difficult to use or handle or manage because of size or weight or shape
unmentionable	adjective	unsuitable or forbidden as a topic of conversation
unmoderated	adjective	not made less extreme
unmodified	adjective	not changed in form or character
unnerved	adjective	deprived of courage and strength
unnoticeable	adjective	not noticeable; not drawing attention
unordered	adjective	not arranged in order
unpalatable	adjective	not pleasant or acceptable to the taste or mind
unpersuasive	adjective	not capable of persuading
unquestionable	adjective	incapable of being questioned
unquestioning	adjective	not inclined to ask questions
unranked	adjective	not arranged in order hierarchically
unrecognised	adjective	not having a secure reputation
unreliability	noun	the trait of not being dependable or reliable
unrequited	adjective	not returned in kind
unsanitary	adjective	not sanitary or healthful
unsealed	adjective	not established or confirmed
unserviceable	adjective	not ready for service
unsubstantiated	adjective	unsupported by other evidence
unsupervised	adjective	not supervised or under constant observation
unsympathetic	adjective	not sympathetic or disposed toward
untenable	adjective	impossible to defend against objection
untold	adjective	too much to be measured
unusable	adjective	not capable of being used
unwholesome	adjective	detrimental to physical or moral well-being
unwise	adjective	showing or resulting from lack of judgment or wisdom
upbeat	adjective	pleasantly (even unrealistically) optimistic
uplink	noun	a transmission from Earth to a spacecraft or the path of such a transmission
uptick	noun	a transaction in the stock market at a price above the price of the preceding transaction
urethritis	noun	inflammation of the urethra; results in painful urination
usurp	verb	to seize a position or power wrongfully
vaccinated	adjective	having been rendered unsusceptible to a disease
vacillate	verb	to waver between choices
vagueness	noun	unclearness by virtue of being poorly expressed or not coherent in meaning
vapid	adjective	offering nothing of interest; flat
vaporized	adjective	converted into a gas or vapor
veering	noun	the act of turning aside suddenly
vehement	adjective	showing strong, forceful feeling
venerate	verb	to regard with deep respect
ventilate	verb	expose to cool or cold air so as to cool or freshen
veracity	noun	truthfulness; accuracy
verbose	adjective	using more words than necessary
vernal	adjective	suggestive of youth; vigorous and fresh
vexed	adjective	troubled persistently especially with petty annoyances
viable	adjective	capable of working or surviving
vicarious	adjective	experienced indirectly, through someone else
vigilant	adjective	watchful for danger
vilify	verb	to speak about with abusive disparagement
vindicate	verb	to clear of blame, or to justify
virulent	adjective	bitterly hostile, or severely poisonous
vociferous	adjective	expressing opinions loudly and insistently
volatile	adjective	liable to change rapidly and unpredictably
volley	noun	rapid simultaneous discharge of firearms
vroom	verb	make a loud, roaring sound, as of a car engine, while moving
warble	verb	sing or play with trills, alternating with the half note above or below
wary	adjective	cautious about possible danger
weaken	verb	lessen the strength of
weepy	adjective	liable to weep easily
weirdness	noun	strikingly out of the ordinary
welter	verb	toss, roll, or rise and fall in an uncontrolled way
whacked	adjective	exhausted or worn out
whammy	noun	a serious or devastating setback
whimsical	adjective	playfully odd; given to sudden fancies
whiteness	noun	the quality or state of the achromatic color of greatest lightness
whoosh	verb	move with a sibilant sound
wistful	adjective	quietly longing for something lost
wonky	adjective	turned or twisted toward one side
woozy	adjective	having or causing a whirling sensation; liable to falling
wraith	noun	a mental representation of some haunting experience
wrangle	verb	to quarrel noisily, angrily or disruptively
wrongness	noun	inappropriate conduct
zealous	adjective	filled with intense enthusiasm for a cause
zenith	noun	the highest point reached
zillion	adjective	very large indeterminate number
zinger	noun	a striking or amusing or caustic remark
`

export const CORE_PACK: RawEntry[] = TSV.trim()
  .split('\n')
  .map((line) => {
    const [word, pos, meaning] = line.split('\t')
    return { word, pos: pos || undefined, meaning }
  })
  .filter((e) => e.word && e.meaning)

export const CORE_NAME = 'Core vocabulary (1000 words)'
